export const HomeInv = require('./home_inv.png')
export const ReactJeo = require('./react_jeo.png')
export const CardViews = require('./Card_Views.png')
export const EduStation = require('./Edu_Station.png')
export const CodeRPSite = require('./CodeRPSite.png')